version: '2'

services:
  web:
    container_name: ${CONTAINER_NAME_WEB}
    build: ./web
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ${VOLUME_HTDOCS}:/var/www/html
    links:
      - db
    networks:
      - default


  db:
    container_name: ${CONTAINER_NAME_DB}
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
